### ISSUE TITLE
showing error while I am going to install bangla

### ISSUE THREAD

**Issue by hmtanbir** [arsho/bangla#1]
I want to install this tool but it gives error as like:

```
Collecting bangla
  Downloading bangla-0.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-d5_Eju/bangla/setup.py", line 9, in <module>
        long_description=readme(),
      File "/tmp/pip-build-d5_Eju/bangla/setup.py", line 4, in readme
        with open('README.rst', encoding='utf8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-d5_Eju/bangla/

```

I use python 2.7.12 in Ubuntu 16.04 LTS.

**Comment by arsho** [comment]
Initially I developed it only for Python3. But your contribution made it available for Python 2 also. Thank you.
